version: '3'

services:
  database_tmg:
    image: postgres
    container_name: database_tmg
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=tmg
    network_mode: host
    volumes:
      - ./pgdata:/data/postgres
  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    network_mode: host
  
  # app:
  #   build:
  #     context: .
  #   container_name: ignite-api
  #   volumes:
  #     - .:/app
  #   ports: 
  #     - "3333:3333"
  #   network_mode: host

volumes:
  pgdata:
    driver: local